services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=spaceship
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: jozsefkiss90/spaceship-backend:latest  
    ports:
      - "5056:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - postgres

  frontend:
    image: jozsefkiss90/spaceship-frontend:latest  
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: